#pragma once
#include <iostream>
#include <cstdlib>
#include <vector>
#include <map>
#include <string>
#include <stack>
#include <algorithm>
#include <queue>

void question30();
int  question29();
void question31();
void question32();
void question33();
void question34();
void question35();
void question4();
void question5();
void question6();
void question7();
void question8();
void question11();
void question10();
void question10_1();
void question10_2();
void question10_3();