#pragma once
#include <iostream>
#include <cstdlib>
#include <vector>
#include <map>
#include <string>
#include <stack>
#include <algorithm>
#include <queue>
#include <unordered_map>
//#include <hash_map>


void question30();
int  question29();
void question31();
void question32();
void question33();
void question34();
void question35();
void question4();
void question5();
void question6();
void question7();
void question8();
void question11();
void question10();
void question10_1();
void question10_2();
void question10_3();
void question15();
void question16();
void question21();
void question22();
void question24();
void question25();
void question26();
void question36();
//void question37();
void question38();
void question39();
void question40();
void question42();
void question43();
void question45();
void question49();
void question50();
void question51();
void question52();
void question53();